// src/renderer/preload.js
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('rimletter', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  getAutostart: () => ipcRenderer.invoke('autostart:get'),
  setAutostart: (enable) => ipcRenderer.invoke('autostart:set', enable),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  setRules: (rules) => ipcRenderer.invoke('rules:set', rules),
  resetConfig: () => ipcRenderer.invoke('config:reset'),
  testLetter: (severity) => ipcRenderer.invoke('letter:test', severity),
  reloadPlugins: () => ipcRenderer.invoke('plugins:reload'),
  listPlugins: () => ipcRenderer.invoke('plugins:list'),
  togglePlugin: (name, enabled) => ipcRenderer.invoke('plugins:toggle', name, enabled),
  previewPlugin: (name) => ipcRenderer.invoke('plugins:preview', name),
  openPluginsDir: () => ipcRenderer.invoke('plugins:dir'),
  setPluginConfig: (name, values) => ipcRenderer.invoke('plugins:setConfig', name, values),
  runPluginAction: (name, action) => ipcRenderer.invoke('plugins:action', name, action),
  getState: () => ipcRenderer.invoke('state:get'),
  closeSettings: () => ipcRenderer.invoke('settings:close'),
  onLetter: (cb) => ipcRenderer.on('letter:new', (_e, letter) => cb(letter)),
  onOpenSettings: (cb) => ipcRenderer.on('settings:open', () => cb()),
  onConfigChange: (cb) => ipcRenderer.on('config:changed', (_e, cfg) => cb(cfg)),
  setMouseOver: (over) => ipcRenderer.send('overlay:mouseover', over),
  setLetterRects: (rects) => ipcRenderer.send('overlay:letter-rects', rects),
  onMouseLeaveForce: (cb) => ipcRenderer.on('overlay:mouse-leave-force', () => cb()),
  getUpdateState: () => ipcRenderer.invoke('update:state'),
  checkForUpdate: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (_e, st) => cb(st))
});
